pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // --- ДОБАВЛЕНО JITPACK ДЛЯ WEBSOCKET ---
        maven { url 'https://jitpack.io' }
        // ---------------------------------------
    }
}

rootProject.name = "Client-App"
include ':app'